{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knightmesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "knightmesh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    module-name: {{ .Values.module.name | quote }}
    module-type: {{ .Values.module.type | quote }}
type: Opaque
data:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}
